reports:
	./commission-job.sh "Is this tweet talking about an important economics development" "What are the key economics events this week?" "econ" "01-econ"
	./commission-job.sh "Is this tweet talking about a development in shipping/freight/trucking, or about a new statistic or economic indicator?" "Summarize shipping/freight/trucking and related economic indicators this week" "freight" "02-freight"
	./commission-job.sh "Is this tweet talking about an important whitehouse action?" "Summarize what the White house is up to this week." "whitehouse" "03-whitehouse"
	./commission-job.sh "Is this tweet talking about an important event?" "Summarize important events this week" "mainstream-us-media" "04-mainstream-us-media"
	./commission-job.sh "Is this tweet talking about an important event?" "Summarize important events this week" "us-politics-commentators" "05-mainstream-us-media"
	./commission-job.sh "Is this tweet talking about a Russia/Ukraine event, or about NATO countries' response to it?" "Summarize events related to the Russia/Ukraine war and NATO countries' related actions" "russia-ukraine-nato" "06-russia-ukraine-nato"
	./commission-job.sh "Does this tweet refer to a significant event?" "Summarize significant events as captured by OSINT sources" "osint" "07-venezuela"
	./commission-job.sh "Is this tweet talking about an important event in Venezuela" "Summarize What happened in and around Venezuela this week." "venezuela" "08-venezuela"
	./commission-job.sh "Is this tweet talking about a disease outbreak, new paper, administrative action, etc?" "Summarize biorisk news last week" "biorisk" "09-biorisk"
	./commission-job.sh "Is this tweet talking about a significant technological development?" "Summarize reported technological developments last week" "general-tech" "10-tech"
	./commission-job.sh "Is this tweet talking about a cyberattack?" "Summarize cyberattack news last week" "cyber" "11-cyber"
	./commission-job.sh "Is this tweet talking about a development in climate?" "Summarize climate developments last week" "climate" "12-climate"
	./commission-job.sh "Is this tweet talking about a natural disaster or storm that has or will affect over 10,000 people?" "Summarize natural disasters this week" "natural-disasters" "13-natural-disasters"
	./commission-job.sh "Is this tweet talking about agricultural developments?" "Summarize aggricultural developments, across production, but also commodities trade &c last week." "natural-disasters" "14-agriculture"
	./commission-job.sh "Is this tweet talking about a new worrying solar flare or sun-related event?" "Summarize the state of the sun last week" "natural-disasters" "15-solar"

